name: Build and Push Docker Image

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository code
            - name: Checkout code
              uses: actions/checkout@v3

            # Generate Image Tags
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v4
              with:
                images: |
                    esouza99/http-color
                tags: |
                    type=raw,value=latest
                    type=ref,event=branch
                    type=ref,event=pr
                    type=semver,pattern={{version}}
                    type=semver,pattern={{major}}.{{minor}}
                    type=raw,value={{date 'YYYYMMDD'}}-{{sha}}

            # Log in to Docker Hub using secrets
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{secrets.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_PASSWORD}}

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                context: ./http-color
                file: ./http-color/Dockerfile
                push: true
                tags: ${{ steps.meta.outputs.tags }}