name: Build and Push Docker Image

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # Checkout the repository code
            - name: Checkout code
              uses: actions/checkout@v3

            # Generate Image Tags
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v4
              with:
                images: |
                    esouza99/http-color
                tags: |
                    type=raw,value=latest
                    type=ref,event=branch
                    type=ref,event=pr
                    type=semver,pattern={{version}}
                    type=semver,pattern={{major}}.{{minor}}
                    type=raw,value={{date 'YYYYMMDD'}}-{{sha}}

            # Log in to Docker Hub using secrets
            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ${{secrets.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_PASSWORD}}

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                context: ./
                file: ./Dockerfile
                push: true
                tags: ${{ steps.meta.outputs.tags }}

            - name: Aqua Security Trivy - Vulnerability Scanner
              uses: aquasecurity/trivy-action@0.24.0
              with:
                  scan-type: "image"
                  image-ref: "esouza99/http-color:latest"
                  exit-code: "1"
                  ignore-unfixed: true
                  vuln-type: "os,library"
                  severity: "CRITICAL"
                  format: "table"